name: clean_architecture_basics
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
